apiVersion: v1
kind: Namespace
metadata:
  name: yapi
  labels:
    env: yapi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: yapi
spec:
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: yapi
  namespace: yapi
spec:
  ports:
    - name: yapi
      port: 3000
      targetPort: 3000
  selector:
    app: yapi
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: yapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      env: yapi
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        env: yapi
    spec:
      containers:
        - name: mongodb
          image: mongo:3.5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yapi
  namespace: yapi
spec:
  selector:
    matchLabels:
      app: yapi
      env: yapi
  template:
    metadata:
      labels:
        app: yapi
        env: yapi
    spec:
      containers:
        - name: yapi
          image: branchzero/yapi:1.7.0
          command: ["/bin/bash"]
          args: ["-c", "npm run install-server && npm run start"]
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /home/yapi/config.json
              name: yapi-config
      volumes:
        - name: yapi-config
          hostPath:
            path: /Users/zhangwei/Documents/Code/github/yapi-docker/config.json
            type: File